name: Veracode Scan 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build Maven
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
        mvn clean package install
        pwd
        ls -l  
    - name: Salvando artefato
      uses: actions/upload-artifact@v3
      with:
        name: verademo.war
        path: target/verademo.war

  Veracode_Policy_Scan:
    name: Veracode Policy Scan
    runs-on: ubuntu-latest
    needs: [build] # executa apenas após o job do build concluir
    steps:
      - uses: actions/checkout@v2
      - name: get archive
        uses: actions/download-artifact@v3 # realiza o download do verademo.war
        with:
          name: verademo.war
          path: target/verademo.war
      - name: Veracode Policy Scan
        uses: veracode/veracode-uploadandscan-action@0.2.4 # usa o plugin oficial da veracode para executar o scan
        with:
          appname: 'Java-VeraDemo' # nome do perfil cadastrado na Veracode
          createprofile: true # nao cria um perfil novo
          filepath: 'target/verademo.war' # busca pelo artefato buildado para subir para o scan
          vid: '${{ VERACODE_API_VID }}' # credencial api
          vkey: '${{ VERACODE_API_KEY }}' # credencial api
          deleteincompletescan: 2     # se tiver um scan travado ele apaga e inicia um novo

  Veracode-SAST-Pipeline-Scan:
    runs-on: ubuntu-latest
    container:
      image: veracode/pipeline-scan:latest
      options: --user root
    steps:
      - name: checkout
        uses: actions/checkout@master
          
      - name: scan 
        run: |
          java -jar pipeline-scan.jar -vid $(VERACODE_API_ID) -vkey $(VERACODE_API_KEY) -f target/verademo.war --fail_on_severity="Very High, High"

  Veracode_Software_Composition_Analisys:
    runs-on: ubuntu-latest
    name: Veracode SCA Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run SCA Scan
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        run: |
          export SRCCLR_SCM_URI="https://github.com/matthlimax/verademo-java-web.git"
          curl -sSL https://download.sourceclear.com/ci.sh | bash -s scan $EXTRA_ARGS

      - name: Executar a varredura do SourceClear
        run: |
          result=$(curl -sSL https://download.sourceclear.com/ci.sh | bash -s -- scan --update-advisor --uri-as-name --allow-dirty)