name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Veracode CLI
        run: |
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode package --source . --type directory --output ${{ github.workspace }}/artifact --trust
          ls -l ${{ github.workspace }}/artifact

      - name: Run Veracode Package
        run: |
          ./veracode package --source . --type directory --output ${{ github.workspace }}/artifact --trust
          ls -l ${{ github.workspace }}/artifact
        env:
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_KEY }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: upload
          path: ${{ github.workspace }}/artifact/verademo.war

  sast_branch_scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: upload

      - name: Verify Veracode CLI
        run: |
          ls -l ./veracode
          which veracode

      - name: Run Veracode SAST - Branch Scan
        run: |
          ./veracode scan --source ${{ github.workspace }}/verademo.war --type directory --output ${{ github.workspace }}/sast --trust
        env:
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_KEY }}

  sast_quick_and_compliance_scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: upload

      - name: Verify Veracode CLI
        run: |
          ls -l ./veracode
          which veracode

      - name: Run Veracode SAST - Compliance Scan
        run: |
          ./veracode scan --source ${{ github.workspace }}/verademo.war --type directory --output ${{ github.workspace }}/sast --trust

      - name: Quick Scan
        run: |
          curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
          unzip -o pipeline-scan-LATEST.zip
          java -jar pipeline-scan.jar -vid ${{ secrets.VERACODE_ID }} -vkey ${{ secrets.VERACODE_KEY }} -f ${{ github.workspace }}/verademo.war --issue_details true -pn "Veracode Recommended Medium" || true

  container_build_and_scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Container Scan
        run: |
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode scan --source ghcr.io/daniel-marchi/redtalks.veracode.sdlc.app/vera:${{ github.run_id }} --type image --format table
        env:
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_KEY }}
